register:
    path: /register
    controller: App\Controller\AuthController::register
    methods: POST

api:
    path: /api2
    controller: App\Controller\AuthController::api

login_check:
    path:     /login_check
    methods:  [POST]

validation:
    path:     /api/product/validateCart/{id}
    controller: App\Controller\ProductController::validateCart

productByCategory:
  path:     /api/product/category/{id}
  controller: App\Controller\ProductController::category
