register:
    path: /register
    controller: App\Controller\AuthController::register
    methods: POST

api:
    path: /api2
    controller: App\Controller\AuthController::api

login_check:
    path:     /login_check
    methods:  [POST]
